@startuml

abstract class Mixinproxy
interface InterfaceOne
interface InterfaceTwo
interface InterfaceBoth

ClassOne <|-- InterfaceOne
ClassTwo <|-- InterfaceTwo
InterfaceBoth <|-- InterfaceOne
InterfaceBoth <|-- InterfaceTwo
Mixinproxy <|-- InterfaceBoth
Mixinproxy <|-- ClassOne
Mixinproxy <|-- ClassTwo

@enduml